# Generated by Django 5.0.3 on 2025-05-17 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='idUser',
        ),
        migrations.AddField(
            model_name='producto',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='tienda.tienda'),
            preserve_default=False,
        ),
    ]
