# Generated by Django 5.0.3 on 2025-04-10 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=255)),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='tienda.tienda')),
            ],
        ),
    ]
